<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('LY'. $this->translate('My ZF2 Playground'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/style.css')
                    ->appendStylesheet($this->basePath() . '/css/prettify.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>


    <!-- Scripts -->
    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js')
    ->appendFile($this->basePath() . '/js/bootstrap.js')
    ->appendFile($this->basePath() . '/js/prettify.js')
?>

  </head>

  <body onload="prettyPrint()">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Under Developing') ?></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
              <li ><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
              <li ><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Blog') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer class="pagination-centered">
        <p>&copy; This site is under developing, comming soon... <?php echo $this->translate('All rights reserved by Liu Yuan.') ?></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
