<?php
$title = 'Add new blog';
$this->headTitle($title);
?>
<div class="row">
<div class="span12">
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
$form = $this->form;
$form->setAttribute('action',$this->url('blog',array('action'=>'add')));
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')->setAttribute('value',$id));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('body'));
echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form);
?>
</div>
</div>
