<?php
$title = 'My blog';
$this->headTitle($title);

//self-made view helpers, not registered yet.
function array2str($array)
{
    $str = implode(' ', $array);
    return $str;
}
function getBrief($str, $needle_s='<brief>', $needle_e='</brief>')
{
    $end = strpos($str, $needle_e);
    $start = strpos($str, $needle_s)+strlen('<brief>');
    if($end === false){
        return array('string'=>$str,
                    'state'=>false);
    }else{
        return array('string'=>substr($str, $start, $end),
                    'state'=>true);
    }
}
?>

<div class="row">
<div class="span4 bs-docs-sidebar" >
<ul class="nav nav-list bs-docs-sidenav" data-spy="affix" data-offset-top="0">
          <li class="active"><a href="#dropdowns"><i class="icon-chevron-right"></i> Dropdowns</a></li>
          <li><a href="#buttonGroups"><i class="icon-chevron-right"></i> Button groups</a></li>
          <li><a href="#buttonDropdowns"><i class="icon-chevron-right"></i> Button dropdowns</a></li>
          <li><a href="#navs"><i class="icon-chevron-right"></i> Navs</a></li>
          <li><a href="#navbar"><i class="icon-chevron-right"></i> Navbar</a></li>
          <li><a href="#breadcrumbs"><i class="icon-chevron-right"></i> Breadcrumbs</a></li>
          <li><a href="#pagination"><i class="icon-chevron-right"></i> Pagination</a></li>
          <li><a href="#labels-badges"><i class="icon-chevron-right"></i> Labels and badges</a></li>
          <li><a href="#typography"><i class="icon-chevron-right"></i> Typography</a></li>
          <li><a href="#thumbnails"><i class="icon-chevron-right"></i> Thumbnails</a></li>
          <li><a href="#alerts"><i class="icon-chevron-right"></i> Alerts</a></li>
          <li><a href="#progress"><i class="icon-chevron-right"></i> Progress bars</a></li>
          <li><a href="#media"><i class="icon-chevron-right"></i> Media object</a></li>
          <li><a href="#misc"><i class="icon-chevron-right"></i> Misc</a></li>
        </ul>
</div>
<div class="span8">
    <H1 class="inl"><?php echo $this->escapeHtml($title);?></H1>
    <a class="btn" href="<?php echo $this->url('blog', array('action'=>'add')); ?>"><i class="icon-plus"></i></a>
<table class="table">
<?php foreach($entries as $entry) : ?>
<tr><td><H3 class="inl"><a href="
<?php echo $this->url('blog',
                    array('action'=>'read',
                    'id'=>$entry->getArrayCopy()['id']));?>
"><?php echo $this->escapeHtml($entry->getArrayCopy()['title']);?></a></H3>
<span class="muted">
    <?php echo date("Y-m-d H:i:s", strtotime($entry->getArrayCopy()['time_altered']));?>
 </span><br/>
<br\>
<?php
    $brief = getBrief($entry->getArrayCopy()['body']);
    echo $brief['string'];
    if($brief['state']){
        echo '<a href="'.
        $this->url('blog',
                    array('action'=>'read',
                    'id'=>$entry->getArrayCopy()['id'])).
            '"> >>></a>';
    }
?>
</td>
</tr>
<?php endforeach; ?>
</table>
</div><!--end of span10-->
</div>
