<?php
$title = $blogEntry->getArrayCopy()['title'];
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span4">
    <p> Place Holder:
        Sidebar here.
    </p>
    </div>
    <div class="span6">
        <div class="main">
        <legend><?php echo $this->escapeHtml($title);?></legend>
        <?php echo $blogEntry->getArrayCopy()['body'];?>
        </div>
    </div>
</div>

